/**
 * Tests for the recurrence engine: the follow-up raid itself (DST, fresh roster,
 * idempotency, weekly limit) and the series guard rails (zombie pause, channel loss).
 */

jest.mock('../../database/client');
jest.mock('../../commands/raid', () => ({
  createRaidEmbed: jest.fn().mockResolvedValue({ title: 'embed' }),
  parseRoleInput: jest.fn(() => ({ validIds: ['role-raider'], invalidNames: [] })),
}));
jest.mock('../../utils/rolePreference', () => ({
  getEffectivePrefsMap: jest.fn(async () => new Map()),
}));
jest.mock('../entitlementService', () => ({
  tryConsumeWeeklyRaid: jest.fn(async () => ({ allowed: true, remaining: 4, max: 5, resetAt: null })),
}));

import { Prisma } from '@prisma/client';
import prisma from '../../database/client';
import { tryConsumeWeeklyRaid } from '../entitlementService';
import {
  advanceSeries,
  createFollowUpRaid,
  hasPlayerInteraction,
  resolveSeriesTail,
  sendPostRaidNudge,
  ZOMBIE_PAUSE_AFTER,
} from '../recurringRaidService';

/** Map with the discord.js Collection helpers the production code uses. */
class MockCollection<K, V> extends Map<K, V> {
  some(fn: (value: V) => boolean): boolean {
    for (const value of this.values()) if (fn(value)) return true;
    return false;
  }
}

function member(id: string, roleIds: string[], displayName = id) {
  const roles = new MockCollection<string, any>();
  for (const roleId of roleIds) roles.set(roleId, { id: roleId, name: roleId });
  return { user: { bot: false, id }, roles: { cache: roles }, displayName };
}

/**
 * Baseline raid: a Thursday 20:00 Berlin raid that has just closed, generated by an
 * earlier instance of its own series.
 */
function sourceRaid(overrides: Record<string, any> = {}): any {
  return {
    id: 'raid-source',
    guildId: 'guild-1',
    teamId: 'team-1',
    channelId: 'channel-1',
    messageId: 'message-1',
    raidDate: new Date('2026-10-22T18:00:00.000Z'), // 20:00 Berlin, CEST
    description: 'Weekly Raid',
    roles: 'role-raider',
    status: 'closed',
    createdBy: 'leader-1',
    recurrenceRule: 'weekly',
    recurrenceParentId: 'raid-older',
    recurrenceActive: true,
    recurrenceSilentStreak: 0,
    nudgeSentAt: null,
    nudgeMessageId: null,
    ...overrides,
  };
}

describe('recurringRaidService', () => {
  let client: any;
  let channel: any;
  let guild: any;
  let membersCache: MockCollection<string, any>;

  beforeEach(() => {
    jest.clearAllMocks();
    jest.spyOn(console, 'log').mockImplementation(() => {});
    jest.spyOn(console, 'error').mockImplementation(() => {});

    membersCache = new MockCollection<string, any>();
    membersCache.set('raider-a', member('raider-a', ['role-raider']));
    membersCache.set('raider-b', member('raider-b', ['role-raider']));
    membersCache.set('bot', { ...member('bot', ['role-raider']), user: { bot: true, id: 'bot' } });
    membersCache.set('outsider', member('outsider', ['role-other']));

    guild = {
      id: 'guild-1',
      members: { cache: membersCache, fetch: jest.fn().mockResolvedValue(undefined), me: null },
    };

    channel = {
      id: 'channel-1',
      isTextBased: () => true,
      send: jest.fn().mockResolvedValue({ id: 'message-new' }),
      messages: { fetch: jest.fn() },
    };

    client = {
      guilds: { fetch: jest.fn().mockResolvedValue(guild) },
      channels: { fetch: jest.fn().mockResolvedValue(channel) },
    };

    (prisma.guild.findUnique as jest.Mock).mockResolvedValue({
      id: 'guild-1',
      language: 'en',
      timezone: 'Europe/Berlin',
    });
    (prisma.raid.findFirst as jest.Mock).mockResolvedValue(null);
    (prisma.raid.create as jest.Mock).mockImplementation(async ({ data }: any) => ({
      id: 'raid-new',
      ...data,
    }));
    (prisma.raid.update as jest.Mock).mockResolvedValue({});
    (prisma.raidAttendance.createMany as jest.Mock).mockResolvedValue({ count: 2 });
    (prisma.raidAttendance.count as jest.Mock).mockResolvedValue(0);
    (prisma.userPreference.upsert as jest.Mock).mockResolvedValue({});
    // clearAllMocks keeps implementations, so the module-level default is restored here
    // rather than leaking a "limit reached" stub into every later test.
    (tryConsumeWeeklyRaid as jest.Mock).mockResolvedValue({
      allowed: true,
      remaining: 4,
      max: 5,
      resetAt: null,
    });
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('createFollowUpRaid', () => {
    it('schedules the next instance one week later in the guild zone, not +604800000ms', async () => {
      const source = sourceRaid();

      const result = await createFollowUpRaid(client, source, { mode: 'inherit' });

      expect(result.ok).toBe(true);
      const created = (prisma.raid.create as jest.Mock).mock.calls[0][0].data;
      // Berlin left CEST in between: the same 20:00 slot is 19:00 UTC, not 18:00.
      expect(created.raidDate.toISOString()).toBe('2026-10-29T19:00:00.000Z');
      expect(created.raidDate.getTime() - source.raidDate.getTime()).not.toBe(7 * 24 * 3600 * 1000);
    });

    it('rebuilds the roster from current role membership instead of copying attendance', async () => {
      // A raider joined the role since last week, another one left the server.
      membersCache.delete('raider-b');
      membersCache.set('raider-new', member('raider-new', ['role-raider']));

      await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      const rows = (prisma.raidAttendance.createMany as jest.Mock).mock.calls[0][0].data;
      expect(rows.map((r: any) => r.userId).sort()).toEqual(['raider-a', 'raider-new']);
      // Everyone starts attending; last week's opt-outs do not carry over.
      expect(rows.every((r: any) => r.status === 'attending')).toBe(true);
      expect(rows.every((r: any) => r.raidId === 'raid-new')).toBe(true);
      // Bots and members without the raid role stay out.
      expect(rows.map((r: any) => r.userId)).not.toContain('bot');
      expect(rows.map((r: any) => r.userId)).not.toContain('outsider');
    });

    it('carries the series forward and links the successor to its parent', async () => {
      await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit', silentStreak: 2 });

      const created = (prisma.raid.create as jest.Mock).mock.calls[0][0].data;
      expect(created.recurrenceParentId).toBe('raid-source');
      expect(created.recurrenceRule).toBe('weekly');
      expect(created.recurrenceActive).toBe(true);
      expect(created.recurrenceSilentStreak).toBe(2);
    });

    it('creates a one-off follow-up without a rule in nudge mode', async () => {
      await createFollowUpRaid(client, sourceRaid({ recurrenceRule: null }), {
        mode: 'none',
        createdBy: 'clicker-1',
      });

      const created = (prisma.raid.create as jest.Mock).mock.calls[0][0].data;
      expect(created.recurrenceRule).toBeNull();
      expect(created.recurrenceParentId).toBe('raid-source');
      expect(created.createdBy).toBe('clicker-1');
    });

    it('is idempotent: an existing successor stops the run before anything is written', async () => {
      (prisma.raid.findFirst as jest.Mock).mockResolvedValue({ id: 'raid-already-there' });

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'duplicate' });
      expect(prisma.raid.create).not.toHaveBeenCalled();
      // Crucially, a re-run must not burn a weekly raid slot either.
      expect(tryConsumeWeeklyRaid).not.toHaveBeenCalled();
    });

    it('treats a unique-constraint collision as a duplicate, not an error', async () => {
      // Two scheduler ticks racing: the loser hits the UNIQUE index on recurrenceParentId.
      (prisma.raid.create as jest.Mock).mockRejectedValue(
        new Prisma.PrismaClientKnownRequestError('unique', {
          code: 'P2002',
          clientVersion: '5.22.0',
        }),
      );

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'duplicate' });
      expect(channel.send).not.toHaveBeenCalled();
    });

    it('reports the weekly limit instead of creating the raid', async () => {
      (tryConsumeWeeklyRaid as jest.Mock).mockResolvedValue({
        allowed: false,
        remaining: 0,
        max: 5,
        resetAt: new Date(),
      });

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'weekly_limit', max: 5 });
      expect(prisma.raid.create).not.toHaveBeenCalled();
    });

    it('reports a deleted channel', async () => {
      client.channels.fetch.mockRejectedValue(new Error('Unknown Channel'));

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'channel_unavailable' });
      expect(prisma.raid.create).not.toHaveBeenCalled();
    });

    it('reports an empty roster', async () => {
      membersCache.clear();

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'no_members' });
    });

    it('rolls the raid back when the message cannot be posted', async () => {
      channel.send.mockRejectedValue(new Error('Missing Permissions'));
      (prisma.raid.delete as jest.Mock).mockResolvedValue({});

      const result = await createFollowUpRaid(client, sourceRaid(), { mode: 'inherit' });

      expect(result).toEqual({ ok: false, reason: 'channel_unavailable' });
      // Otherwise the orphan row would permanently occupy the successor slot.
      expect(prisma.raid.delete).toHaveBeenCalledWith({ where: { id: 'raid-new' } });
    });
  });

  describe('advanceSeries — zombie guard', () => {
    it('pauses the series once three consecutive auto-raids saw no interaction', async () => {
      const raid = sourceRaid({ recurrenceSilentStreak: ZOMBIE_PAUSE_AFTER - 1 });
      (prisma.raidAttendance.count as jest.Mock).mockResolvedValue(0);

      await advanceSeries(client, raid);

      expect(prisma.raid.update).toHaveBeenCalledWith({
        where: { id: 'raid-source' },
        data: { recurrenceActive: false },
      });
      expect(prisma.raid.create).not.toHaveBeenCalled();
      // The pause is announced with a resume button.
      const notice = channel.send.mock.calls[0][0];
      expect(notice.components[0].toJSON().components[0].custom_id).toBe('raid_resume_raid-source');
    });

    it('keeps going while the streak is still below the threshold', async () => {
      const raid = sourceRaid({ recurrenceSilentStreak: ZOMBIE_PAUSE_AFTER - 2 });

      const result = await advanceSeries(client, raid);

      expect(result.ok).toBe(true);
      const created = (prisma.raid.create as jest.Mock).mock.calls[0][0].data;
      expect(created.recurrenceSilentStreak).toBe(ZOMBIE_PAUSE_AFTER - 1);
    });

    it('resets the streak as soon as a single player interacts', async () => {
      (prisma.raidAttendance.count as jest.Mock).mockResolvedValue(1);
      const raid = sourceRaid({ recurrenceSilentStreak: ZOMBIE_PAUSE_AFTER - 1 });

      const result = await advanceSeries(client, raid);

      expect(result.ok).toBe(true);
      expect((prisma.raid.create as jest.Mock).mock.calls[0][0].data.recurrenceSilentStreak).toBe(0);
    });

    it('never counts a hand-created raid as silent', async () => {
      // No parent → a leader made this one, which is engagement by definition.
      const raid = sourceRaid({ recurrenceParentId: null, recurrenceSilentStreak: 2 });

      const result = await advanceSeries(client, raid);

      expect(result.ok).toBe(true);
      expect((prisma.raid.create as jest.Mock).mock.calls[0][0].data.recurrenceSilentStreak).toBe(0);
    });

    it('pauses instead of retrying when the weekly limit blocks the series', async () => {
      (tryConsumeWeeklyRaid as jest.Mock).mockResolvedValue({
        allowed: false,
        remaining: 0,
        max: 5,
        resetAt: new Date(),
      });

      await advanceSeries(client, sourceRaid());

      expect(prisma.raid.update).toHaveBeenCalledWith({
        where: { id: 'raid-source' },
        data: { recurrenceActive: false },
      });
      expect(channel.send).toHaveBeenCalled();
    });

    it('pauses silently when the channel is gone — there is nowhere to post a notice', async () => {
      client.channels.fetch.mockRejectedValue(new Error('Unknown Channel'));

      await advanceSeries(client, sourceRaid());

      expect(prisma.raid.update).toHaveBeenCalledWith({
        where: { id: 'raid-source' },
        data: { recurrenceActive: false },
      });
      expect(channel.send).not.toHaveBeenCalled();
    });

    it('does not pause a series just because the successor already exists', async () => {
      (prisma.raid.findFirst as jest.Mock).mockResolvedValue({ id: 'raid-already-there' });

      await advanceSeries(client, sourceRaid());

      expect(prisma.raid.update).not.toHaveBeenCalled();
    });
  });

  describe('hasPlayerInteraction', () => {
    it('is false for a roster nobody touched', async () => {
      (prisma.raidAttendance.count as jest.Mock).mockResolvedValue(0);
      await expect(hasPlayerInteraction('raid-1')).resolves.toBe(false);
      expect(prisma.raidAttendance.count).toHaveBeenCalledWith({
        where: { raidId: 'raid-1', interactedAt: { not: null } },
      });
    });

    it('is true once one row carries an interaction stamp', async () => {
      (prisma.raidAttendance.count as jest.Mock).mockResolvedValue(1);
      await expect(hasPlayerInteraction('raid-1')).resolves.toBe(true);
    });
  });

  describe('sendPostRaidNudge', () => {
    it('posts the prompt and records that this raid has had its one nudge', async () => {
      await sendPostRaidNudge(client, sourceRaid({ recurrenceRule: null }));

      const posted = channel.send.mock.calls[0][0];
      expect(posted.components[0].toJSON().components[0].custom_id).toBe('raid_nudge_raid-source');
      expect(prisma.raid.update).toHaveBeenCalledWith({
        where: { id: 'raid-source' },
        data: { nudgeSentAt: expect.any(Date), nudgeMessageId: 'message-new' },
      });
    });

    it('still marks the attempt when the channel is gone, so it is never retried', async () => {
      client.channels.fetch.mockRejectedValue(new Error('Unknown Channel'));

      await sendPostRaidNudge(client, sourceRaid({ recurrenceRule: null }));

      expect(prisma.raid.update).toHaveBeenCalledWith({
        where: { id: 'raid-source' },
        data: { nudgeSentAt: expect.any(Date), nudgeMessageId: null },
      });
    });
  });

  describe('resolveSeriesTail', () => {
    it('walks the chain to the newest instance', async () => {
      (prisma.raid.findUnique as jest.Mock).mockResolvedValue({ id: 'raid-1' });
      (prisma.raid.findFirst as jest.Mock)
        .mockResolvedValueOnce({ id: 'raid-2' })
        .mockResolvedValueOnce({ id: 'raid-3' })
        .mockResolvedValueOnce(null);

      await expect(resolveSeriesTail('raid-1')).resolves.toEqual({ id: 'raid-3' });
    });

    it('returns null for an unknown raid', async () => {
      (prisma.raid.findUnique as jest.Mock).mockResolvedValue(null);
      await expect(resolveSeriesTail('nope')).resolves.toBeNull();
    });
  });
});
